"""Display-only constants for the OpenCV GUI.

Gameplay timing/rules stay in `constants.py`.
Visual look-and-feel for the client lives here.
"""

# Window / assets
WINDOW_NAME = 'KungFuChess'
BOARD_IMAGE_NAME = 'board.png'
PIECES_DIR_NAME = 'pieces'
DEFAULT_CELL_SIZE = 100

# Colors are OpenCV BGR(A).
SELECTED_BORDER_COLOR = (0, 255, 255, 255)
LEGAL_MOVE_DOT_COLOR = (70, 220, 70, 255)
GAME_OVER_BACKGROUND_COLOR = (35, 35, 190, 255)
GAME_OVER_TEXT_COLOR = (255, 255, 255, 255)
LONG_REST_BACKGROUND_COLOR = (160, 255, 255, 255)
AIRBORNE_BACKGROUND_COLOR = (255, 245, 180, 255)
JUMP_LABEL_COLOR = (245, 245, 245, 255)

# Overlays and chrome
REST_OVERLAY_ALPHA = 0.55
LEGAL_DOT_MIN_RADIUS = 4
LEGAL_DOT_RADIUS_DIVISOR = 9
SELECTION_BORDER_MIN_THICKNESS = 1
SELECTION_BORDER_DIVISOR = 50

# Labels
JUMP_LABEL = 'jump'
GAME_OVER_LABEL = 'Game Over'
JUMP_LABEL_FONT_MIN = 0.35
JUMP_LABEL_FONT_DIVISOR = 160.0
JUMP_LABEL_THICKNESS = 1
GAME_OVER_FONT_MIN = 0.5
GAME_OVER_FONT_DIVISOR = 45.0
GAME_OVER_THICKNESS_MIN = 1
GAME_OVER_THICKNESS_DIVISOR = 25
GAME_OVER_BANNER_MIN_RATIO = 4

# Piece sprite states used by the view
STATE_IDLE = 'idle'
STATE_MOVE = 'move'
STATE_JUMP = 'jump'
STATE_LONG_REST = 'long_rest'
STATE_SHORT_REST = 'short_rest'

# Idle bob / jump hop (pixel layout)
IDLE_BOB_PERIOD_MS = 1400.0
IDLE_BOB_RATIO = 0.03
IDLE_BOB_PHASE_ROW = 7
IDLE_BOB_PHASE_COL = 13
IDLE_BOB_PHASE_SCALE = 0.35
JUMP_HEIGHT_RATIO = 0.28

# Animation loop pacing (OpenCV waitKey) — mirrored in img.py defaults.
ANIMATION_MAX_FRAME_MS = 50
ANIMATION_ACTIVE_DELAY_MS = 16
ANIMATION_IDLE_DELAY_MS = 30
